version: '3.9'

services:
  app:
    container_name: DPDB_django
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 [::1]"
      - SQL_DATABASE=DPDB_db_dev
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    env_file:
      - ./dev.env
    depends_on:
      - db

  db:
    container_name: DPDB_postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DPDB_db_dev

volumes:
  postgres_data:
